apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | default "frontend.example.com" }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | default "/" }}
            pathType: {{ .pathType | default "Prefix" }}
            frontend:
              service:
                name: frontend-service
                port:
                  number: 80
          {{- end }}
    {{- end }}
