apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.hosts.host | default "frontend.example.com" }} # Optional: Specify a hostname if using a custom domain
      http:
        paths:
          - path: {{ .Values.ingress.paths.path | default "/" }}
            pathType: {{ .Values.ingress.paths.pathType | default "Prefix" }}
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
