version: '3.8'

services:
  frontend:
    image: frontend_image
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    container_name: frontend

  backend:
    image: backend_image
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    networks:
      - app_network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    container_name: backend

networks:
  app_network:
    driver: overlay
