image:
  repository: navjotrai/frontend_image
  tag: latest7

service:
  type: ClusterIP
  port: 80

spec:
  replicas: 3 

ingress:
  enabled: true
  hosts:
    - host: chatsapp.xyz
      paths:
        - path: /
          pathType: Prefix

nginx:
  configMapName: nginx-config
