image:
  repository: navjotrai/frontend_image
  tag: latest

service:
  type: ClusterIP
  port: 80

spec:
  replicas: 3 

ingress:
  enabled: true
  hosts:
    - host: frontend.example.com
      paths:
        - path: /
          pathType: Prefix

nginx:
  configMapName: nginx-config
